In [66]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.datasets import load_iris
from sklearn import tree
import graphviz 
import os


data = pd.read_csv('./0724_timeseries_banana_taipei.csv')
data


date  banana_Price
0     2011-01-01          26.9
1     2011-01-02          28.9
2     2011-01-03          28.9
3     2011-01-04          30.7
4     2011-01-05          31.0
...          ...           ...
3813  2021-06-10          25.8
3814  2021-06-11          25.1
3815  2021-06-12          25.3
3816  2021-06-13          26.1
3817  2021-06-14          26.6

[3818 rows x 2 columns]

In [38]:
data2 = pd.read_csv('./台北一分析資料.csv')
data2

日期  banana_平均價  banana_交易量  scarletbanana_平均價  guava_平均價  \
0     2011-01-01        26.9     15779.0               39.0       43.4   
1     2011-01-02        28.9     17462.0               47.0       48.2   
2     2011-01-03        28.9     17462.0               47.0       48.2   
3     2011-01-04        30.7     19405.0               40.1       43.6   
4     2011-01-05        31.0     22050.0               40.0       44.4   
...          ...         ...         ...                ...        ...   
3813  2021-06-10        25.8     18943.0               33.6       25.9   
3814  2021-06-11        25.1     18309.0               31.6       23.0   
3815  2021-06-12        25.3     15720.0               35.6       23.1   
3816  2021-06-13        26.1     15004.0               28.0       22.0   
3817  2021-06-14        26.6     15039.0               39.3       23.2   

      banana_前日平均價  banana_5日平均價  
0             26.9          29.3  
1             26.9          29.3  
2             28.9          29.3  
3             28.9          29.3  
4             30.7          29.3  
...            ...           ...  
3813          23.5          24.1  
3814          25.8          24.4  
3815          25.1          24.8  
3816          25.3          25.2  
3817          26.1          25.8  

[3818 rows x 7 columns]

In [39]:
# data2['日期']
data2['year'] = data2['日期'].apply(lambda x:int(x.split('-')[0]))
data2['month'] = data2['日期'].apply(lambda x:int(x.split('-')[1]))
data2['day'] = data2['日期'].apply(lambda x:int(x.split('-')[2]))

In [40]:
data2.drop(['日期'], axis=1)

banana_平均價  banana_交易量  scarletbanana_平均價  guava_平均價  banana_前日平均價  \
0           26.9     15779.0               39.0       43.4          26.9   
1           28.9     17462.0               47.0       48.2          26.9   
2           28.9     17462.0               47.0       48.2          28.9   
3           30.7     19405.0               40.1       43.6          28.9   
4           31.0     22050.0               40.0       44.4          30.7   
...          ...         ...                ...        ...           ...   
3813        25.8     18943.0               33.6       25.9          23.5   
3814        25.1     18309.0               31.6       23.0          25.8   
3815        25.3     15720.0               35.6       23.1          25.1   
3816        26.1     15004.0               28.0       22.0          25.3   
3817        26.6     15039.0               39.3       23.2          26.1   

      banana_5日平均價  year  month  day  
0             29.3  2011      1    1  
1             29.3  2011      1    2  
2             29.3  2011      1    3  
3             29.3  2011      1    4  
4             29.3  2011      1    5  
...            ...   ...    ...  ...  
3813          24.1  2021      6   10  
3814          24.4  2021      6   11  
3815          24.8  2021      6   12  
3816          25.2  2021      6   13  
3817          25.8  2021      6   14  

[3818 rows x 9 columns]

In [58]:
col_price=['banana_平均價', 'scarletbanana_平均價', 'guava_平均價', 'banana_前日平均價', 'banana_5日平均價']
data2[col_price] = data2[col_price]*10
data2

日期  banana_平均價  banana_交易量  scarletbanana_平均價  guava_平均價  \
0     2011-01-01       269.0     15779.0              390.0      434.0   
1     2011-01-02       289.0     17462.0              470.0      482.0   
2     2011-01-03       289.0     17462.0              470.0      482.0   
3     2011-01-04       307.0     19405.0              401.0      436.0   
4     2011-01-05       310.0     22050.0              400.0      444.0   
...          ...         ...         ...                ...        ...   
3813  2021-06-10       258.0     18943.0              336.0      259.0   
3814  2021-06-11       251.0     18309.0              316.0      230.0   
3815  2021-06-12       253.0     15720.0              356.0      231.0   
3816  2021-06-13       261.0     15004.0              280.0      220.0   
3817  2021-06-14       266.0     15039.0              393.0      232.0   

      banana_前日平均價  banana_5日平均價  year  month  day  
0            269.0         293.0  2011      1    1  
1            269.0         293.0  2011      1    2  
2            289.0         293.0  2011      1    3  
3            289.0         293.0  2011      1    4  
4            307.0         293.0  2011      1    5  
...            ...           ...   ...    ...  ...  
3813         235.0         241.0  2021      6   10  
3814         258.0         244.0  2021      6   11  
3815         251.0         248.0  2021      6   12  
3816         253.0         252.0  2021      6   13  
3817         261.0         258.0  2021      6   14  

[3818 rows x 10 columns]

In [61]:
data2[col_price] = data2[col_price].astype(int)
data2

日期  banana_平均價  banana_交易量  scarletbanana_平均價  guava_平均價  \
0     2011-01-01         269     15779.0                390        434   
1     2011-01-02         289     17462.0                470        482   
2     2011-01-03         289     17462.0                470        482   
3     2011-01-04         307     19405.0                401        436   
4     2011-01-05         310     22050.0                400        444   
...          ...         ...         ...                ...        ...   
3813  2021-06-10         258     18943.0                336        259   
3814  2021-06-11         251     18309.0                316        230   
3815  2021-06-12         253     15720.0                356        231   
3816  2021-06-13         261     15004.0                280        220   
3817  2021-06-14         266     15039.0                393        232   

      banana_前日平均價  banana_5日平均價  year  month  day  
0              269           293  2011      1    1  
1              269           293  2011      1    2  
2              289           293  2011      1    3  
3              289           293  2011      1    4  
4              307           293  2011      1    5  
...            ...           ...   ...    ...  ...  
3813           235           241  2021      6   10  
3814           258           244  2021      6   11  
3815           251           248  2021      6   12  
3816           253           252  2021      6   13  
3817           261           258  2021      6   14  

[3818 rows x 10 columns]

In [63]:
X = data2[['banana_交易量','scarletbanana_平均價', 'guava_平均價', 'banana_前日平均價', 'banana_5日平均價','year', 'month', 'day']].to_numpy()
y = data2['banana_平均價']
y

0       269
1       289
2       289
3       307
4       310
       ... 
3813    258
3814    251
3815    253
3816    261
3817    266
Name: banana_平均價, Length: 3818, dtype: int32

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train)
print(type(X_train))
print('===========')
print(y_train)
scaler = preprocessing.StandardScaler().fit(X_train)

X_train = scaler.transform(X_train)


model = RandomForestClassifier(max_depth=None, n_estimators=100)
model.fit(X_train, y_train)

X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)

print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('con_matrix: {}'.format(con_matrix))

[[1.7430e+04 3.4000e+02 3.7100e+02 ... 2.0210e+03 2.0000e+00 1.0000e+00]
 [3.5253e+04 2.7200e+02 4.4300e+02 ... 2.0180e+03 4.0000e+00 1.6000e+01]
 [1.9343e+04 5.5900e+02 1.5700e+02 ... 2.0160e+03 4.0000e+00 1.1000e+01]
 ...
 [2.8203e+04 3.1500e+02 3.6500e+02 ... 2.0150e+03 1.0000e+00 2.1000e+01]
 [2.7525e+04 3.1200e+02 3.0600e+02 ... 2.0130e+03 1.1000e+01 1.9000e+01]
 [1.5310e+04 3.2800e+02 3.3800e+02 ... 2.0140e+03 2.0000e+00 2.0000e+01]]
<class 'numpy.ndarray'>
3684    204
2662    164
1927    645
2813    250
1616    233
       ... 
350     178
2497    211
1481    339
1053    446
1146    470
Name: banana_平均價, Length: 3054, dtype: int32
number of correct sample: 181
accuracy: 0.2369109947643979
con_matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
